package main

func main() {
	RunCustomError()
}
